### DISCUSSION TITLE
dracula/dracula-theme outdated submodules?

### DISCUSSION THREAD

**Discussion by tonystr** [dracula/dracula-theme#445] [General] [answered]
Hey! Maybe this should go under issues, but I'm a bit confused about the behavior of submodules(?) linked in [dracula/dracula-theme](https://github.com/dracula/dracula-theme). The one titled gamemaker-studio [links to](https://github.com/dracula/gamemaker-studio/tree/daf6fd04b375b03dbd6e3d2b62fc3ad4732a3f5c) an older version of the [game-maker repository](https://github.com/dracula/gamemaker-studio/tree/master). See picture below:

![image](https://user-images.githubusercontent.com/30723101/90289773-e0f9ce00-de7c-11ea-8c30-ff0e282d2aa1.png)

Do these submodules need to be updated manually? Is there no way to simply have them link to the most up-to-date master branch? I just had someone contact me about not seeing recent changes to the theme, because they had followed the link in the dracula/dracula-theme repository

**Comment by benknoble** [comment]
Git submodules stay "pinned" at a version until they're updated. AFAIK, @zenorocha is the only who can/does update them, so yeah, it's kind of manual (`git submodule update --remote`, I think).

**Comment by zenorocha** [comment, marked as answer]
That's right, from time to time I manually run `git submodule update --recursive --remote` to update all the submodules.

I'm open to suggestions on how to improve this process.

**Reply by OptimalNoob** [reply]
Would a github action do the trick here?

```
name: Update Submodules
on:
  schedule:
    - cron: '0 0 1 * *' 
  workflow_dispatch:  # manual trigger option

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Update submodules
        run: git submodule update --recursive --remote
```
