### ISSUE TITLE
[New Port Request] Dracula Theme for Markdown files

### ISSUE THREAD

**Issue by MelihDarcanxyz** [dracula/dracula-theme#799]
I would love to see dracula theme for markdown files through markdown-specific html or pandoc. Currenct pandoc theme doesn't comply with the dracula specification considering Markup section.

**Comment by MelihDarcanxyz** [comment]
I just created this ```scss``` file by converting md to html first and then creating rules for them according to dracula specs. This might help.

```scss
$background-lighter: #424450;
$background-light: #343746;
$background: #282A36;
$background-dark: #21222C;
$background-darker: #191A21;
$foreground: #F8F8F2;
$selection: #44475A;
$comment: #6272A4;
$red: #FF5555;
$orange: #FFB86C;
$yellow: #F1FA8C;
$green: #50FA7B;
$purple: #BD93F9;
$cyan: #8BE9FD;
$pink: #FF79C6;

* {
    background-color: $background;
    color: $foreground;
}

@for $i from 1 through 6 {

    h#{$i} {
      color: $purple;
      font-weight: bold;
    }
}

em,
i {
    color: $yellow;
    font-style: italic;
}

strong,
b {
    color: $orange;
    font-weight: bold;
}

ul,
ol {
    li {
        &::marker {
            color: $cyan;
        }
    }
}

a {
    text-decoration: none;
    color: $pink;

    &:visited {
        color: $cyan;
    }
}

code {
    background-color: $background-light;
    color: $green;
}

blockquote {
    p {
        background-color: $background-light;
        color: $yellow;
        font-style: italic;
    }
}

pre {
    code {
        background-color: $background-light;
        color: $orange;
    }
}

hr {
    color: $comment;
}
```
